### ISSUE TITLE
[Help] How to compile?

### ISSUE THREAD

**Issue by ghost** [m-x-d/KMQuake2#1]
I apologize if I didn't look hard enough, but I couldn't find any instructions or tutorials on how to compile this for Windows. What software do I need and how do I do this? I'm new to this stuff. Are there precompiled binaries by chance like there is for YamagiQ2?

Thx in advance

**Comment by m-x-d** [comment]
This is a personal project currently in development, which is not yet intended for public use. That's why there's no description / manual / compiling instructions / downloadable binaries yet.

Compiling is straightforward: open "projects\VS2017\kmquake2.sln" in Visual Studio 2017 with C++ package installed (VS 2019 should work too, but I haven't tested that), switch solution configuration to "Release", build "kmquake2" and "kmq2gamex86" projects.

The only quirk is that when building in Release mode, VS will copy the binaries to Quake 2 folder.
If you want to change the path to said folder (it's currently set to "d:\Games\Quake 2 clean\"), open "projects\VS2017\kmquake2\kmquake2.props" in a text editor and change the value of "GameDir" property.
If you want to disable this behaviour, open Properties window of both "kmquake2" and "kmq2gamex86" projects, switch Configuration to "Release" and set "Build Events" -> "Post-Build Event" -> "Use In Build" to "No".
